version: "3"
services:

  # React 
  react:
    container_name: 'frontend'
    build:
      context: './frontend'
      args: 
        APP_NAME: $APP_NAME
        CLIENT_ROOT: $CLIENT_ROOT
    env_file:
      - '.env'
    volumes:
      - './frontend:/usr/src'
    ports:
      - '18080:3000'
    tty: true
    stdin_open: true

  # koa
  koa:
    container_name: 'backend'
    build:
      context: './backend'
      args: 
        APP_NAME: $APP_NAME
        SERVER_ROOT: $SERVER_ROOT
    env_file:
      - '.env'
    volumes:
      - ./backend/api:/opt/api
    #  - /opt/api/node_modules:
    ports:
      - '18081:3000'
    tty: true
    stdin_open: true
    links:
      - db

  db:
    container_name: mysql
    image: mysql:5.6
    ports:
      - '3306:3306'
    env_file:
      - '.env'
    volumes:
      - './backend/sql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
