version: "3"
services:
  # express
  express:
    container_name: 'backend'
    build:
      context: './backend'
      args: 
        APP_NAME: $APP_NAME
        SERVER_ROOT: SERVER_ROOT
    env_file:
      - '.env'
    volumes:
      - './backend:/usr/src'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
  # Vue
  vuejs:
    container_name: 'frontend'
    build:
      context: './frontend'
      args: 
        APP_NAME: $APP_NAME
    env_file:
      - '.env'
    volumes:
      - './frontend:/app'
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
  #  links:

  #    - mysql-server
  # DB
  #mysql-server:
  #  image: mysql:5.6
  #  volumes:
  #   - './sql:/docker-entrypoint-initdb.d'
  #  environment:
  #    MYSQL_ROOT_PASSWORD: 'pass'
