version: '3'
services:
  koa:
    container_name: koa
    build:
      context: .
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./api:/opt/api
#ここから
    links:
      - db

  db:
    container_name: mysql
    image: mysql:5.6
    ports:
      - '3306:3306'
    volumes:
      - './sql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
